### PR TITLE
Reviews list api data

### PR DESCRIPTION
**Pull request by jwhooperjr**
Trello story:
https://trello.com/c/wJBHEqYK - As a user, I want to be able to see reviews created by other users so that I can decide if I want the product or not

### CODE REVIEW

**Comment by morahan** [comment]
Needs work to pass linter.  try using the quick fix to 'auto-fix' issues

**Review by morahan — COMMENTED** [review]
run:  "npm run lint" to find errors

**Review by morahan — CHANGES_REQUESTED** [review]
Try hovering over the red squigglies and then click quick fix> then at bottom of list you can auto fix all auto-fixable problems. Also, you could use the following command to make the linter ignore your file:  /* eslint-disable */

**Review by shawnsull3 — APPROVED** [review]
Looks good. thanks for fixing those errors.

**Comment by shawnsull3** [comment]
@morahan You might need to approve this or something. John fixed the eslint errors, but I'm blocked from merging it do the change requested

**Review by morahan — APPROVED** [review]
Nice work!

**Pull request merged**
